FROM openjdk:8-alpine
ADD ./JenkinBuildWork/JenkinBuildDeploy/serviceregigtry-0.0.1-SNAPSHOT.jar serviceregigtry-0.0.1-SNAPSHOT.jar
EXPOSE 9001
ENTRYPOINT ["java", "-jar", "serviceregigtry-0.0.1-SNAPSHOT.jar"]
