FROM openjdk:8-alpine
ADD ./serviceregigtry/target/serviceregigtry-0.0.1-SNAPSHOT.jar serviceregigtry-0.0.1-SNAPSHOT.jar
EXPOSE 90001
ENTRYPOINT ["java", "-jar", "serviceregigtry-0.0.1-SNAPSHOT.jar"]
